#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    #print(s)
    militaryTime = s.split(":")
    #print(militaryTime)
    if((int(militaryTime[0]) == 12 and militaryTime[2][2:] == "PM") or ((int(militaryTime[0])) != 12 and militaryTime[2][2:] == "AM")):
        return militaryTime[0] + ":" + militaryTime[1] + ":" + militaryTime[2][0:2]
    else:
        militaryHour = int(militaryTime[0])
        #print(militaryHour)
        militaryHour += 12
        #print(militaryHour)
        
        if militaryHour >= 24:
            militaryTime[0] = "00"
        #print(militaryTime[0])
        else:
            militaryTime[0] = str(militaryHour)
            if len(militaryTime[0]) == 1:
                militaryTime[0] = "0" + str(militaryHour)
        #remove pm from answer
        #militarySecond = militaryTime[2][0:2]
        
        print(militaryTime[0] + ":" + militaryTime[1] + ":" + militaryTime[2][0:2])    
        return militaryTime[0] + ":" + militaryTime[1] + ":" + militaryTime[2][0:2]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
